# Generated by Django 5.1.5 on 2025-06-13 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todolist",
            old_name="task",
            new_name="title",
        ),
    ]
