# Generated by Django 5.1.5 on 2025-06-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "Usuário", "verbose_name_plural": "Usuários"},
        ),
    ]
