# Generated by Django 5.1.5 on 2025-06-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_alter_usuario_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="username",
        ),
    ]
